SELab-2/UGent-4

- frontend/frontend/src/pages/addChangeAssignmentPage/AddChangeAssignmentPage.tsx
- frontend/frontend/src/pages/addChangeAssignmentPage/RestrictionsDialog.tsx
- frontend/frontend/src/pages/mainPage/CoursesView.tsx
> wegwerken errors, website zou horen te werken

- api/docker/python_entrypoint.py
- api/docker/rundocker.sh
- api/docker/testing_entrypoint.sh
- api/models/indiening.py
- api/serializers/indiening.py
- api/urls.py
- api/views/indiening.py
@ArnoutAllaert kon jij me nog helpen om deze pull request als een draft te zetten? Vind da niet direct
> Verder werken aan docker artefacten genereren en docker te laten werken

- frontend/frontend/src/pages/assignmentPage/AssignmentPage.tsx
Naar de juiste branch deze keer
> indieningen worden herladen wanneer nieuwe indiening word gedaan

- frontend/frontend/src/components/AssignmentListItem.tsx
- frontend/frontend/src/components/CourseCard.tsx
- frontend/frontend/src/components/SubmissionListItemStudentPage.tsx
- frontend/frontend/src/components/SubmissionListItemTeacherPage.tsx
- frontend/frontend/src/pages/addChangeAssignmentPage/AddChangeAssignmentPage.tsx
- frontend/frontend/src/pages/assignmentPage/AssignmentPage.tsx
- frontend/frontend/src/pages/scoresPage/StudentScoreListItem.tsx
- frontend/frontend/src/pages/subjectsPage/AssignmentListItemSubjectsPage.tsx
- frontend/frontend/src/pages/submissionPage/SubmissionPage.tsx
Overal waar data staan, staat nu ook het tijdstip
Alle date-time's zijn nu ook volgens hetzelfde formaat namelijk "DD/MM/YYYY HH:mm"
> Tijdstippen toevoegen aan data

- frontend/frontend/src/pages/groupsPage/GroupsPage.tsx
parameter vak vervangen door project zodat dit overeen komt met de backend
> kleine fix groepen pagina

- frontend/frontend/src/components/CourseCard.tsx
- frontend/frontend/src/i18n/en.ts
- frontend/frontend/src/i18n/nl.ts
- frontend/frontend/src/pages/mainPage/CoursesView.tsx
- frontend/frontend/src/pages/mainPage/MainPage.tsx
Vakken worden in de juiste tab getoond en kunnen gearchiveerd worden. (in theorie: er zat nog een fout in de backend die nog nie op de server staat)
Projecten worden nog niet automatisch gearchiveerd wanneer hun vak gearchiveerd word, maar dit lijkt mij beter om in de backend op te lossen dan de frontend.
> Archiveer vakken

- frontend/frontend/src/pages/subjectsPage/ProjectsView.tsx
> aantal indieningen word correct getoond op SubjectsPage voor studenten

- frontend/frontend/src/components/CourseCard.tsx
- frontend/frontend/src/pages/mainPage/ArchivedView.tsx
- frontend/frontend/src/pages/mainPage/CoursesView.tsx
- frontend/frontend/src/pages/mainPage/MainPage.tsx
Vakken kunnen nu gepind worden op de mainPage
De volgorde van de vakken veranderd slechts als de pagina herladen word, want dit voelt beter aan.
Pas op: je kan enkel vakken pinnen waarvoor je ingeschreven bent als dezelfde rol als die op je gebruiker account (lesgever of student)
> Vakken pinnen

- api/models/indiening.py
- api/models/vak.py
- api/serializers/gebruiker.py
- api/serializers/groep.py
- api/serializers/vak.py
- api/urls.py
- api/utils.py
- api/views/gebruiker.py
- api/views/groep.py
- api/views/indiening.py
- api/views/project.py
- api/views/restrictie.py
- api/views/score.py
- api/views/vak.py
Twee nieuwe velden toegevoegd aan het model Vak, gearchiveerd en jaartal
> Extra werk aan de backend (bug fixes, extra implementatie)

- frontend/frontend/src/components/CopyToClipboard.tsx
- frontend/frontend/src/i18n/en.ts
- frontend/frontend/src/i18n/nl.ts
- frontend/frontend/src/pages/subjectsPage/SubjectsPage.tsx
- frontend/frontend/src/routes.tsx
Implementatie van invitation link. Hoe zouden jullie dit willen? #79 
https://github.com/SELab-2/UGent-4/assets/48103261/21ee49c1-692e-4529-a156-c288174fbefa
https://github.com/SELab-2/UGent-4/assets/48103261/c99a3020-4d65-46dd-980f-705651b8325d
> invitation links zijn geimplementeerd in de frontend.

- frontend/frontend/src/pages/subjectsPage/AddChangeSubjectPage.tsx
[issue](https://github.com/SELab-2/UGent-4/issues/185#issuecomment-2092742486)
> clear input if teacher/student is added to course

- frontend/frontend/src/pages/subjectsPage/AddChangeSubjectPage.tsx
Minstens 1 lesgever per vak, verwijderknop wordt afgezet indien er nog maar 1 lesgever aanwezig is.
[Screencast from 2024-05-03 12-37-52.webm](https://github.com/SELab-2/UGent-4/assets/48103261/7a95d96a-d3a0-4d62-9aff-8679b0166a21)
#208
> minstens 1 lesgever in  vak

- frontend/frontend/src/components/Header.tsx
- frontend/frontend/src/components/LanguageSwitcher.tsx
- frontend/frontend/vite.config.ts
implementatie talen + wereldbol ivp  account knop
> wegwerken accountknop in header. gebruik taal switch in header

- frontend/frontend/src/pages/groupsPage/GroupsPage.tsx
console logs weggehaald en wat internationalisatie toegevoegd
> groupPage opschonen

- frontend/frontend/src/components/DeadlineCalendar.tsx
- frontend/frontend/src/i18n/en.ts
- frontend/frontend/src/i18n/nl.ts
- frontend/frontend/src/pages/mainPage/MainPage.tsx
Er zal wel nog wat visuele opmaak moeten gebeuren, het ziet er nog niet zeer goed uit.
> Kalender uitbreiding met klikbare deadlines is toegevoegd

- frontend/frontend/src/components/Header.tsx
- frontend/frontend/src/components/SubmissionListItemTeacherPage.tsx
- frontend/frontend/src/pages/submissionPage/SubmissionPage.tsx
- frontend/frontend/vite.config.ts
paar kleine fixes voor de frontend, meeste overblijfselen van slechte merge
> kleine fixes

- frontend/frontend/src/components/DeadlineCalendar.tsx
- frontend/frontend/src/components/Header.tsx
- frontend/frontend/src/i18n/en.ts
- frontend/frontend/src/i18n/nl.ts
- frontend/frontend/src/pages/assignmentPage/AssignmentPage.tsx
- frontend/frontend/src/pages/subjectsPage/ProjectsView.tsx
- frontend/frontend/src/pages/subjectsPage/SubjectsPage.tsx
- frontend/frontend/src/pages/submissionPage/SubmissionPage.tsx
Pull request om alle fouten in de frontend door dingen over het hoofd te zien met aanpassingen
> veel errors in frontend ->fix branch

- api/admin.py
- api/models/project.py
- api/models/template.py
- api/serializers/project.py
- api/serializers/vak.py
- api/urls.py
- api/utils.py
- api/views/indiening.py
- api/views/template.py
- Groepen aanmaken gebeurd nu automatisch in de backend. Er zullen altijd genoeg groepen zijn voor het aantal leerlingen in een vak
Laat weten als er nog dingen in de backend moeten veranderd/toegevoegd worden
> Backend extras

- frontend/frontend/src/pages/addChangeAssignmentPage/AddChangeAssignmentPage.tsx
- frontend/frontend/src/pages/subjectsPage/AddChangeSubjectPage.tsx
er kon geen nieuw project aangemaakt worden omdat de gebruiker niet werd ingeladen
> error met inladen user

- frontend/frontend/src/pages/assignmentPage/AssignmentPage.tsx
bovenste van dubbele opgave verwijdert
> dubbele opgave is weg

- frontend/frontend/src/pages/addChangeAssignmentPage/AddChangeAssignmentPage.tsx
- frontend/frontend/src/pages/addChangeAssignmentPage/RestrictionTemplateUI.tsx
- frontend/frontend/src/pages/addChangeAssignmentPage/RestrictionsDialog.tsx
verwijderen restricties mogelijk + toevoegknop verplaatst
> Restrictions list view

- frontend/frontend/src/components/TabSwitcher.tsx
- frontend/frontend/src/pages/mainPage/ArchivedView.tsx
- frontend/frontend/src/pages/mainPage/CoursesView.tsx
- frontend/frontend/src/pages/mainPage/MainPage.tsx
> positie jaarkiezer verandert

- frontend/frontend/src/components/AssignmentListItem.tsx
- frontend/frontend/src/components/CourseCard.tsx
- frontend/frontend/src/components/Header.tsx
- frontend/frontend/src/components/TabSwitcher.tsx
- frontend/frontend/src/i18n/en.ts
- frontend/frontend/src/i18n/nl.ts
- frontend/frontend/src/pages/assignmentPage/AssignmentPage.tsx
- frontend/frontend/src/pages/groupsPage/GroupsPage.tsx
- frontend/frontend/src/pages/mainPage/CoursesView.tsx
- frontend/frontend/src/pages/mainPage/MainPage.tsx
- frontend/frontend/src/pages/scoresPage/ProjectScoresPage.tsx
- frontend/frontend/src/pages/subjectsPage/AddChangeSubjectPage.tsx
- frontend/frontend/src/pages/subjectsPage/AssignmentListItemSubjectsPage.tsx
- frontend/frontend/src/pages/subjectsPage/SubjectsPage.tsx
- frontend/frontend/src/pages/submissionPage/SubmissionPage.tsx
> Student group switch. Eerst deze mergen!!!!

- api/models/indiening.py
- Zorgen dat indiening bestanden niet worden verwijderd
> Kleine bugfix

- frontend/frontend/src/pages/submissionPage/SubmissionPage.tsx
> regex + filename

- api/views/groep.py
Een extra check ingevoerd die kijkt of de gebruiker permissies heeft (lesgever of superuser is) of wel gewoon zichzelf wil verwijderen/toevoegen in een groep
> Permissie breach oplossen bij groepen

- api/models/indiening.py
- Bestanden werden niet deftig in hun juiste datafolder gestoken (gefixt)
> Backend fixes

- api/models/indiening.py
…Bestanden van indieningen weer proberen fixen, werkt lokaal maar niet op server
> Backend indiening fix
